### ISSUE TITLE
Support update from Odata Connected Service

### ISSUE THREAD

**Issue by marcioafoliveira** [unchase/Unchase.Odata.Connectedservice#5]
I have a service that I created with Odata Connected Service on VS 2017.
I can add a new one but I can't update it.

We really need this feature.

**Comment by unchase** [comment]
You created the file with [Unchase Odata Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice&ssr=false#overview) or with [Odata Connected Service](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) by Microsoft?
Can you re-generate the specification file (by creating it again) and try to update it?

**Comment by marcioafoliveira** [comment]
OData Connected Service by Microsoft

**Comment by unchase** [comment]
[My service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) cannot update the client-code created by the [OData Connected Service](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) by Microsoft, because they have different *productId* (*providerId*) of the Connected service.
Instead, you can re-generate the code from an existing json-specification URI using my service, and then update it when required.

But I will see if I can somehow to solve this issue.

**Comment by marciooliveiraprimaverabss** [comment]
updates?

**Comment by unchase** [comment]
Hi, @marcioafoliveira.

It will be ready in the next release.

**Comment by unchase** [comment]
Fixed in v1.3.0.

**Comment by marciooliveiraprimaverabss** [comment]
I have version 1.3.1 of Unchase Odata Connected Service and I still can't update my Odata Service. 
I just can add.

**Comment by unchase** [comment]
Why do you need the ability to update client code with an unsupported Connected Service by Microsoft when you can generate it using the [Unchase OData Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice), and update it later when you like?
The generated code will not differ so much that compatibility is broken.

I added a button so that you can load similar data from a json-file to generate client code.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello,

I have issue OrgContext not generatd in reference.cs, can  anyone help me please

Cordially
